## 1.基本操作
- 一维数组称为向量(Vector)
- 二维数组称为矩阵(Matrix)
- 三维及以上的数组称为张量(Tensor)

使用Pytorch创建张量：

In [1]:
import torch

x = torch.arange(12)
print(x) # print the tensor itself
print(x.shape) # print tensor's dimension
print(x.numel()) # print the amount of elements

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


使用reshape改变张量的维度:

In [2]:
print(x.reshape(3, 4)) # 3 rows and 4 columns
print(x.reshape(6, -1)) # implicit conversion: 6 x 2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


创建全0或者全1的张量：

In [3]:
zeros = torch.zeros(2, 3, 4)
ones = torch.ones(2, 4, 3)
print(zeros, '\n', ones)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]) 
 tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


也可以从某一种概率分布中随机采样张量的值，比如从标准正态分布中进行采样：

In [4]:
torch.randn(3, 4, 5)

tensor([[[ 0.0477, -0.1350, -0.3571,  1.4261,  1.1622],
         [ 0.2566,  0.0716,  0.5388, -1.4949,  1.9727],
         [ 0.6398, -0.2441,  1.8211,  0.8761, -0.2762],
         [-0.1340, -0.5802,  2.2840,  0.8114, -1.1410]],

        [[ 0.4563, -0.5710,  0.0425,  2.0620, -0.6339],
         [-0.9171,  1.6123,  0.6503,  0.3571,  0.1727],
         [-0.0396, -0.6308, -0.2663, -0.0926,  0.1735],
         [-0.7028, -0.2000,  0.5715, -0.0191,  0.1890]],

        [[ 2.2350,  0.8446,  1.6527, -0.4551,  0.7662],
         [ 0.0257,  0.1703, -0.1272, -0.0982,  2.3473],
         [ 0.0330, -0.2166,  0.8339, -0.3783,  1.0316],
         [ 0.8488,  1.5294, -0.5692,  1.5056,  0.4827]]])

或者指定张量中每个元素的值：

In [5]:
my_tensor = torch.tensor([[1, 2, 3], [2, 3, 4], [4, 5, 6], [7, 8, 9]])
print(my_tensor)
assert my_tensor.shape == (4, 3)

tensor([[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6],
        [7, 8, 9]])


## 2.运算
对张量进行基本的运算：

In [6]:
x = torch.arange(start=0, end=24, step=2).reshape(3,4)
y = torch.arange(start=1, end=24, step=2).reshape(3,4)
print(' x :', x)
print(' y :', y)
# ==========二元运算=============
print('x+y:', x+y)
print('y-x:', y-x)
print('x*y:', x*y)
print('x/y:', x/y)

# ==========一元运算=============
print(torch.exp(x))
print(x.sum())

# ==========非降维求和===========
sum_x = x.sum(axis=0, keepdims=True)
print(sum_x)

# ==========转置张量=============
print(x.T)

# ==========克隆张量=============
copy_x = x.clone()
print(copy_x == x)
id(copy_x) == id(x) # 克隆时，为新的张量开辟了新的内存空间

 x : tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])
 y : tensor([[ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
x+y: tensor([[ 1,  5,  9, 13],
        [17, 21, 25, 29],
        [33, 37, 41, 45]])
y-x: tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
x*y: tensor([[  0,   6,  20,  42],
        [ 72, 110, 156, 210],
        [272, 342, 420, 506]])
x/y: tensor([[0.0000, 0.6667, 0.8000, 0.8571],
        [0.8889, 0.9091, 0.9231, 0.9333],
        [0.9412, 0.9474, 0.9524, 0.9565]])
tensor([[1.0000e+00, 7.3891e+00, 5.4598e+01, 4.0343e+02],
        [2.9810e+03, 2.2026e+04, 1.6275e+05, 1.2026e+06],
        [8.8861e+06, 6.5660e+07, 4.8517e+08, 3.5849e+09]])
tensor(132)
tensor([[24, 30, 36, 42]])
tensor([[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


False

也可以对两个张量进行联接(concat):

In [7]:
z1 = torch.cat((x, y), dim=0)
z2 = torch.cat((x, y), dim=1)
print(z1)
print(z2)

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [ 1,  3,  5,  7],
        [ 9, 11, 13, 15],
        [17, 19, 21, 23]])
tensor([[ 0,  2,  4,  6,  1,  3,  5,  7],
        [ 8, 10, 12, 14,  9, 11, 13, 15],
        [16, 18, 20, 22, 17, 19, 21, 23]])


## 3.广播机制
当两个张量形状不一致时，torch的广播机制会对元素进行复制以将两个张量转换为相同形状：

In [8]:
x = torch.ones(2,1)
y = torch.ones(1,3)
print(x)
print(y)
print(x+y) # convert to 2x3


tensor([[1.],
        [1.]])
tensor([[1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


## 4.对张量的索引操作
类似python中的其他可迭代数据结构，张量也支持索引、切片等操作：

In [9]:
z = torch.randn(3,4)
print(z)
print('the second row: ', z[1])
print('the first element of the second row: ', z[1][0])

tensor([[ 0.0763, -1.1010,  1.3481, -0.3526],
        [-1.2038,  0.2268, -0.5616,  1.2748],
        [ 0.8312,  1.2611,  0.0640, -1.3442]])
the second row:  tensor([-1.2038,  0.2268, -0.5616,  1.2748])
the first element of the second row:  tensor(-1.2038)


根据索引，对张量的指定位置进行修改：

In [10]:
z[0,0] = 1
print(z)

tensor([[ 1.0000, -1.1010,  1.3481, -0.3526],
        [-1.2038,  0.2268, -0.5616,  1.2748],
        [ 0.8312,  1.2611,  0.0640, -1.3442]])


## 5.矩阵常见操作
向量点积（Dot product)

In [11]:
x = torch.arange(4)
torch.dot(x,x.T)

tensor(14)

矩阵-向量积

In [12]:
y = torch.arange(12).reshape(-1,4)
torch.mv(y,x)

tensor([14, 38, 62])

矩阵-矩阵积

In [13]:
x = torch.arange(12).reshape(4,-1)
x.mm(y)

tensor([[ 20,  23,  26,  29],
        [ 56,  68,  80,  92],
        [ 92, 113, 134, 155],
        [128, 158, 188, 218]])

范数(norms)反映了一个向量的大小，因此范数一定是非负的，最小为0.其中L2范数是向量个元素平方和的平方根(类似欧几里得距离)：

In [14]:
l = torch.arange(4, dtype=float).reshape(1,-1)
l.norm()

tensor(3.7417, dtype=torch.float64)

与L2范数相比，L1范数受异常值影响更小，即抗干扰能力更强，L1范数即个元素的绝对值之和。

In [15]:
l1 = torch.abs(torch.tensor([3,-4,1])).sum()
print(l1)

tensor(8)


## 6.求导
对函数y = 2x^Tx进行求导，其中函数的输出值y为标量, x为向量：

In [20]:
x = torch.arange(4.0)
x.requires_grad_(True) # 对x求导
y = 2 * torch.dot(x,x.T)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

当求导函数输出值y不为标量时，需要先对y中元素进行求和，再反向传播，求得x的梯度：

In [22]:
x.grad.zero_() # 清除之前的梯度
x.requires_grad_(True)
y = x*x
y.sum().backward()
x.grad # == 2*x

tensor([0., 2., 4., 6.])

考虑如下复合函数情况：
y是关于x的函数，而z是关于y和x的函数，现需要求z关于x的梯度，则将y视为常量，只考虑x在y被计算后的梯度。

In [23]:
x.grad.zero_()
y = x*x
u = y.detach() # consider y as a constant
z = u * x # z = ux, dz/dx = du

z.sum().backward()
x.grad == u

tensor([True, True, True, True])